apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: hoangtrx/notes-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
              # Path within the container at which the volume should be mounted.
              # Must not contain ':'.
            - mountPath: /app/notes
              # Name must be the same as the volume defined in the 'volumes' below
              name: notes-volume
      volumes:
        - name: notes-volume
          # HostPath represents a pre-existing file or directory on the
          # host machine that is directly exposed to the container
          hostPath:
            # On Windows, set the path for directory
            #    C:/Users/user.name/mydir
            # to
            #    /run/desktop/mnt/host/c/Users/user.name/mydir
            path: "/run/desktop/mnt/host/c/Users/hoang.tran/Desktop/Home/Workplace/Containerization/06-notes/notes"
            type: DirectoryOrCreate
      # Uncomment the following piece of config to use an 'emptyDir' volume instead.
      # In such case, also change the 'replicas' (see spec.replicas above) to 1
      # volumes:
      #   - name: notes-volume
      #     # EmptyDir represents a temporary directory that shares a pod's lifetime.
      #     # Meaning that it is only there while the pod is running.
      #     emptyDir: {}
